server:
  port: ${API_GATEWAY_PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
      server:
        webmvc:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=2
            - id: employee-service
              uri: lb://employee-service
              predicates:
                - Path=/api/employees/**
              filters:
                - StripPrefix=2
            - id: application-service
              uri: lb://application-service
              predicates:
                - Path=/api/applications/**
              filters:
                - StripPrefix=2
            - id: housing-service
              uri: lb://housing-service
              predicates:
                - Path=/api/housing/**
              filters:
                - StripPrefix=2
            - id: email-service
              uri: lb://email-service
              predicates:
                - Path=/api/emails/**
              filters:
                - StripPrefix=2

jwt:
  secret: ${JWT_SECRET}
