server:
  port: ${HOUSING_SERVICE_PORT:8084}

spring:
  application:
    name: housing-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/housing_db?useSSL=true&requireSSL=true&serverTimezone=UTC
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
